on:
    workflow_dispatch:

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Checkout
              uses: actions/checkout@v3

            - name: Output branch name
              id: name
              run: |
                  echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

            - name: Push
              # To use latest action, specify "release-master" instead of "v0.0.4"
              uses: jpribyl/push-prebuilt-action@release-master
              with:
                  push-branch: release-${{ steps.name.outputs.branch }}
